# Generated by Django 2.2.1 on 2019-05-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='Duration',
        ),
        migrations.AddField(
            model_name='tour',
            name='Dayduration',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='Hoursduration',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='Monthduration',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
