# Generated by Django 2.2.1 on 2019-05-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190520_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='Dayduration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='Distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='Hoursduration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='Monthduration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
