# Generated by Django 2.2.1 on 2019-05-20 11:01

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190520_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='Tourtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Type'),
        ),
    ]
