# Generated by Django 2.2.1 on 2019-05-20 11:02

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20190520_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='Color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
    ]
