# Generated by Django 2.2.1 on 2019-05-21 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20190521_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=200)),
                ('Author', models.CharField(max_length=60)),
                ('Tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Tour')),
            ],
        ),
    ]
