# Generated by Django 2.2.1 on 2019-05-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_commenttour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='Rout',
        ),
    ]
