# Generated by Django 2.2.1 on 2019-05-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_tour_distinationlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='Accomodation',
        ),
        migrations.AddField(
            model_name='tour',
            name='Accomodation',
            field=models.ManyToManyField(blank=True, null=True, to='web.Accomodation'),
        ),
        migrations.RemoveField(
            model_name='tour',
            name='Language',
        ),
        migrations.AddField(
            model_name='tour',
            name='Language',
            field=models.ManyToManyField(blank=True, null=True, to='web.Language'),
        ),
        migrations.RemoveField(
            model_name='tour',
            name='Meal',
        ),
        migrations.AddField(
            model_name='tour',
            name='Meal',
            field=models.ManyToManyField(blank=True, null=True, to='web.Meal'),
        ),
        migrations.RemoveField(
            model_name='tour',
            name='Transport',
        ),
        migrations.AddField(
            model_name='tour',
            name='Transport',
            field=models.ManyToManyField(blank=True, null=True, to='web.Transport'),
        ),
    ]
