# Generated by Django 2.2.1 on 2019-06-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20190521_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='Googlemap',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
