# Generated by Django 2.2.1 on 2019-06-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField()),
                ('Image', models.ImageField(upload_to='web/static/image/DistImage/')),
                ('Title', models.CharField(max_length=100)),
            ],
        ),
    ]
