# Generated by Django 2.2.1 on 2019-06-03 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0018_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNumber', models.CharField(blank=True, max_length=30, null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('ResrvTime', models.DateTimeField(auto_now_add=True)),
                ('Status', models.CharField(blank=True, max_length=50, null=True)),
                ('Persons', models.IntegerField(blank=True, null=True)),
                ('PyamentStatus', models.CharField(blank=True, max_length=100, null=True)),
                ('Track', models.CharField(blank=True, max_length=50, null=True)),
                ('Order', models.CharField(max_length=20)),
                ('Passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Passenger')),
                ('Tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Tour')),
            ],
        ),
    ]
