# Generated by Django 2.2.1 on 2019-06-18 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_booking_passenger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='Text',
            new_name='Name',
        ),
    ]
