# Generated by Django 2.2.1 on 2019-06-18 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20190618_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='Type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Type'),
        ),
    ]
