# Generated by Django 2.2.1 on 2019-07-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_auto_20190618_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='Email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
