# Generated by Django 2.2.1 on 2019-07-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='PriceText',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
