# Generated by Django 2.2.1 on 2019-07-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_tour_pricetext'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
