# Generated by Django 2.2.1 on 2019-07-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_commenttour_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='web/static/image/SliderImage/')),
                ('Title', models.CharField(blank=True, max_length=100, null=True)),
                ('Link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
