# Generated by Django 2.2.1 on 2019-07-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_mainpageslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Lead',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
